# permissions for end users to view ansibleplaybooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleplaybook-viewer-role
rules:
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooks/status
  verbs:
  - get
