# permissions for end users to view ansibleplaybooktemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleplaybooktemplate-viewer-role
rules:
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooktemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooktemplates/status
  verbs:
  - get
