# permissions for end users to edit ansibleplaybooktemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleplaybooktemplate-editor-role
rules:
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooktemplates/status
  verbs:
  - get
