# permissions for end users to view virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-viewer-role
rules:
- apiGroups:
  - onecloud.yunion.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - virtualmachines/status
  verbs:
  - get
